@startuml

Counter <|-- MultipleCounter


class Counter
{
   - int count
   + Counter()
   + void increment()
   + void decrement()
   + int getCount()
}

class MultipleCounter
{
    -int times
    +MultipleCounter(int times)
    +void increment()
    +void decrement()

}

@enduml